version: "3.7"
services:
  app:
    build:
      args:
        user: rabelo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: upload-data
    container_name: upload-data-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - upload-data

  db:
    image: mysql:5.7
    container_name: upload-data-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - upload-data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: upload-data-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - upload-data
      
  nginx:
    image: nginx:alpine
    container_name: upload-data-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - upload-data 

networks:
  upload-data:
    driver: bridge
